apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/redhat-appstudio/image-controller/config/default?ref=e5a29db5772c85b84d3246597e5b39f229d2925a

images:
- name: quay.io/redhat-appstudio/image-controller
  newName: quay.io/redhat-appstudio/image-controller
  newTag: e5a29db5772c85b84d3246597e5b39f229d2925a

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
