---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/rcerven/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-test_slo
