apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
#  - https://github.com/redhat-appstudio/application-service/config/default?ref=adba93ac28b10c71629ecdf37bdef579fb381582
  - https://github.com/rcerven/application-service/config/default?ref=3997f4f070fd8780dc12e08c5edc6bbce1c073b3


components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
#    newName: quay.io/redhat-appstudio/application-service
#    newTag: adba93ac28b10c71629ecdf37bdef579fb381582
    newName: quay.io/rcerven_rhtaptest/application-operator
    newTag: latest

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace


namespace: application-service
