apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redhat-appstudio-pr-token.yaml
- redhat-appstudio-tekton-catalog-pr-token.yaml
- redhat-appstudio-pr-cronjob.yaml
- redhat-appstudio-tekton-catalog-pr-cronjob.yaml
configMapGenerator:
- name: single-image-pruner-configmap
  files:
  - image_pruner/prune_images.py
namespace: image-controller
