apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-appstudio-tekton-catalog-pr-token
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: production/build/redhat-appstudio-tekton-catalog-pr-token
  refreshInterval: 20h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: redhat-appstudio-tekton-catalog-pr-token
