apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
#- https://github.com/konflux-ci/build-service/config/default?ref=4df8ef4674edee9a10d8682da346271bb9a1783a
- https://github.com/rcerven/build-service/config/default?ref=ceba53080a8ad7fca4ed3b15cb91eee9e6d06563

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
#  newName: quay.io/konflux-ci/build-service
#  newTag: eaf8ddaccd0bf234b5316d5f0f5feee5bbc88984
  newName: quay.io/rcerven_rhtaptest/build-operator
  newTag: latest

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml

configMapGenerator:
  - name: webhook-config
    files:
      - webhook-config.json

components:
  - ../components/rh-certs
  - ../components/webhook-config
