resources:
- allow-argocd-to-manage.yaml
- https://github.com/rcerven/build-service/config/default?ref=e3230907b214b6f49c8569538fd811f665c99d70
- build-pipeline-selectors/build-pipeline-selector.yaml
- monitoring.yaml
- rbac

# Skip applying the build-service operands (BuildPipelineSelector) while the build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: build-service

images:
- name: quay.io/redhat-appstudio/build-service
  newName: quay.io/rcerven_rhtaptest/build-operator
  newTag: latest

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
